SELECT 'CATEGORIE' AS table_name, COUNT(*) AS total FROM CATEGORIE
UNION ALL
SELECT 'FOURNISSEUR', COUNT(*) FROM FOURNISSEUR
UNION ALL
SELECT 'CLIENT', COUNT(*) FROM CLIENT
UNION ALL
SELECT 'PRODUIT', COUNT(*) FROM PRODUIT
UNION ALL
SELECT 'COMMANDE', COUNT(*) FROM COMMANDE
UNION ALL
SELECT 'LIGNE_COMMANDE', COUNT(*) FROM LIGNE_COMMANDE
UNION ALL
SELECT 'AVIS', COUNT(*) FROM AVIS
UNION ALL
SELECT 'STOCK_HISTORIQUE', COUNT(*) FROM STOCK_HISTORIQUE;

SELECT num_commande, montant_total, statut
FROM COMMANDE
ORDER BY num_commande;

SELECT id_ligne, num_commande, code_produit, quantite, prix_unitaire, remise
FROM LIGNE_COMMANDE
ORDER BY id_ligne;

SELECT code_produit, nom, stock, seuil_alerte
FROM PRODUIT
ORDER BY code_produit;