ARCHIVE LOG LIST;

SHUTDOWN IMMEDIATE;

STARTUP MOUNT;

ALTER DATABASE ARCHIVELOG;

ALTER DATABASE OPEN;

ALTER PLUGGABLE DATABASE ALL OPEN;

ALTER PLUGGABLE DATABASE ALL SAVE STATE;

ALTER SYSTEM SET db_recovery_file_dest_size = 10G SCOPE=BOTH;

ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/recovery_area' SCOPE=BOTH;

ARCHIVE LOG LIST;

SHOW PARAMETER db_recovery_file_dest;

SELECT name, open_mode
FROM v$pdbs;